### PR TITLE
[#1] Revamp

### PR DESCRIPTION
**Pull request by joanjeremiah**
Migrated to the new framework

### CODE REVIEW

**Comment by jesperpedersen** [comment]
You need to add instructions on how to built it locally, f.ex.

```
Build Warning: Layout 'home' requested in index.md does not exist.
```

**Comment by joanjeremiah** [comment]
> You need to add instructions on how to built it locally, f.ex.
> 
I will add instructions. Do u want me to squash the commits?

> ```
> Build Warning: Layout 'home' requested in index.md does not exist.
> ```

I don't see this warning when I build the site.

**Comment by jesperpedersen** [comment]
Yes, add the instructions and squash the commits

**Comment by joanjeremiah** [comment]
> Yes, add the instructions and squash the commits

Completed

**Comment by jesperpedersen** [comment]
`http://localhost:5173/` doesn't work...

**Comment by joanjeremiah** [comment]
> `http://localhost:5173/` doesn't work...

Could you please provide a bit more detail on the issue?

**Comment by jesperpedersen** [comment]
I'm following the README.md - so only

```
pnpm install
pnpm --host dev
```

on Fedora 39

**Comment by joanjeremiah** [comment]
Please try running just 'pnpm dev'. I'm not sure what the problem is yet. I will run some tests on my end and get back to you as soon as possible. Could you share the output in your terminal?

**Comment by jesperpedersen** [comment]
Ok, that works now - I'll look it over

**Comment by jesperpedersen** [comment]
We need the tutorials on the site...

**Comment by jesperpedersen** [comment]
"Releases" needs to be reverse sorted

**Comment by jesperpedersen** [comment]
Make sure that you align with `main` as we are up to 13 tutorials now

**Comment by jesperpedersen** [comment]
Align `About` as well against `README.md`

**Comment by joanjeremiah** [comment]
> We need the tutorials on the site...

It is on the index page. Also on the sidebar. I could add to the nav bar if needed.

**Comment by joanjeremiah** [comment]
> Make sure that you align with `main` as we are up to 13 tutorials now

I only see 8 tutorials on the main branch.

**Comment by joanjeremiah** [comment]
> Align `About` as well against `README.md`

I don't get what you mean. about.md is aligned with the main branch.

**Comment by jesperpedersen** [comment]
```
git fetch upstream
git rebase -i upstream/main
```

in the development repository. Well, depending on your setup...

Otherwise - https://github.com/pgmoneta/pgmoneta/blob/main/doc/DEVELOPERS.md#basic-git-guide

**Comment by joanjeremiah** [comment]
I've completed the git rebase as per your instructions. My branch Revamp is now up-to-date with upstream/main, and I've force-pushed the changes to my fork. The rebase was successful without any conflicts, and everything appears to be in order.

**Comment by jesperpedersen** [comment]
I meant you should rebase your pgmoneta.git repository, and then sync the web site against it.

So, f.ex. there should be 13 tutorials in your branch

**Comment by joanjeremiah** [comment]
> I meant you should rebase your pgmoneta.git repository, and then sync the web site against it.
> 
> So, f.ex. there should be 13 tutorials in your branch

I get it now. Do you want this https://github.com/pgmoneta/pgmoneta/tree/main/doc/manual on the website?

**Comment by jesperpedersen** [comment]
This - https://github.com/pgmoneta/pgmoneta/tree/main/doc/tutorial

And, see the latest README.md

**Comment by joanjeremiah** [comment]
@jesperpedersen 
1. Reversed the order of releases
2. Added tutorial docs
3. Changed about.md

**Comment by joanjeremiah** [comment]
> @jesperpedersen
> 
> 1. Reversed the order of releases
> 2. Added tutorial docs
> 3. Changed about.md

@jesperpedersen Is there anything more to be done?

**Comment by jesperpedersen** [comment]
@joanjeremiah Can you rebase, and integrate the latest release ? Then I'll take another look - I think we are mostly there...

**Comment by joanjeremiah** [comment]
> @joanjeremiah Can you rebase, and integrate the latest release ? Then I'll take another look - I think we are mostly there...

Added the latest release and rebased

**Comment by jesperpedersen** [comment]
The tutorial menu - on the left - only contains 8 instead of 13.

The getting started guide says 0.12.0 instead of 0.11.1, and see https://github.com/pgmoneta/pgmoneta/commit/5f01a9e395117917b10b02fc1e15fd8b9bdbea06

**Comment by jesperpedersen** [comment]
Otherwise, it looks good !

**Comment by joanjeremiah** [comment]
> The tutorial menu - on the left - only contains 8 instead of 13.
> 
> The getting started guide says 0.12.0 instead of 0.11.1, and see [pgmoneta/pgmoneta@5f01a9e](https://github.com/pgmoneta/pgmoneta/commit/5f01a9e395117917b10b02fc1e15fd8b9bdbea06)

Added the links on the side bar. Made the necessary changes in gettingstarted.md and 01_install.md

**Comment by jesperpedersen** [comment]
Merged.

Thanks for your contribution !

**Comment by jesperpedersen** [comment]
The site isn't deploying correctly - any ideas ?

See the additional commits, and deployment logs...

**Comment by joanjeremiah** [comment]
I will check it out

**Comment by jesperpedersen** [comment]
The artifact @ https://github.com/pgmoneta/pgmoneta.github.io/actions/runs/8911956148 looks weird...

**Comment by jesperpedersen** [comment]
`pnpm build` fails, but `pnpm dev` works...

**Comment by joanjeremiah** [comment]
I found the issue. There were some dead links which caused the build to fail. I figure dev doesn't consider dead links. I fixed the links. Now it works ( tested it ). I have pushed the changes to the same branch.

**Comment by joanjeremiah** [comment]
Is it possible to reopen this pr? Or do I create a new one?

**Comment by jesperpedersen** [comment]
Create a new one

**Comment by jesperpedersen** [comment]
You rebased on top of my changes, right ?

**Comment by joanjeremiah** [comment]
> You rebased on top of my changes, right ?

No, I am not sure how to do that

**Comment by jesperpedersen** [comment]
You can use https://github.com/pgmoneta/pgmoneta/blob/main/doc/DEVELOPERS.md#basic-git-guide - of course change the upstream URL...

**Comment by joanjeremiah** [comment]
> You can use https://github.com/pgmoneta/pgmoneta/blob/main/doc/DEVELOPERS.md#basic-git-guide - of course change the upstream URL...

This is my upstream URL https://github.com/pgmoneta/pgmoneta.github.io.git rn. what should I change it to?

**Comment by jesperpedersen** [comment]
That is correct... I tried another change - still doesn't work

**Comment by joanjeremiah** [comment]
> Member



> That is correct... I tried another change - still doesn't work

Did you try building the new pr? The build is working fine.

**Comment by jesperpedersen** [comment]
You downgraded some of the version identifiers in `deploy.yml` - I think that is the file with the problems...

**Comment by jesperpedersen** [comment]
Look at https://pgmoneta.github.io/ - nothing gets deployed really

**Comment by joanjeremiah** [comment]
> Look at https://pgmoneta.github.io/ - nothing gets deployed really

This is because of the build fail. In the new pr I have fixed the dead links. Now with the correct deploy.yml, it should work.

**Comment by jesperpedersen** [comment]
But, look at the latest changes - for `deploy.yml`... e.g. resolve the conflict

The rest looks ok to me...

**Comment by joanjeremiah** [comment]
> But, look at the latest changes - for `deploy.yml`... e.g. resolve the conflict
> 
> The rest looks ok to me...

I have pushed a deploy.yml in the new pr. I am not entirely sure if it's the right one.

**Comment by jesperpedersen** [comment]
The problem is that we have those changes already...

**Comment by joanjeremiah** [comment]
Can you share me the link to the correct deploy.yml ?

**Comment by jesperpedersen** [comment]
This is what we have right now - https://github.com/pgmoneta/pgmoneta.github.io/blob/main/.github/workflows/deploy.yml - which doesn't work

**Comment by joanjeremiah** [comment]
Can't we use this https://github.com/pgexporter/pgexporter.github.io/blob/main/.github/workflows/deploy.yml ?

**Comment by joanjeremiah** [comment]
Have you seen my new pr? It fixes the build issues.

**Comment by jesperpedersen** [comment]
Well, apparently that didn't work - see the deployment log @ https://github.com/pgmoneta/pgmoneta.github.io/deployments/github-pages

**Comment by jesperpedersen** [comment]
I'll give it a look in a bit

**Comment by jesperpedersen** [comment]
Ok, running it manually works now -- so there is something funny going on...

**Pull request merged**
